"""
config
"""


DEEPSEEK_API_KEY = " "
DEEPSEEK_BASE_URL = " "
DEEPSEEK_MODEL = " "
DEFAULT_TEMPERATURE = 0

DEFAULT_PROJECT_ROOT = "/path/to/generated_projects"  # where the project generates
DEFAULT_TIMEOUT = 3000

AUTO_INSTALL = True
USE_CONDA = False
OPEN_BROWSER = True
BROWSER_DELAY = 2
MAX_TOKENS = 65536
